export const ApiEndpoints = {
  authLogin: "/api/auth/login",
  authRefresh: "/api/auth/refresh",
  authLogout: "/api/auth/logout",
  config: "/api/config",
  configKeys: "/api/config/keys",
  configEntry: (key: string) => `/api/config/entries/${encodeURIComponent(key)}`,
  categories: "/api/categories",
  categoriesTree: "/api/categories/tree",
  media: "/api/media",
  mediaUpload: "/api/media/upload",
  posts: "/api/posts",
  cmsPosts: "/api/posts/cms",
  postById: (id: string) => `/api/posts/${id}`,
  postPublish: (id: string) => `/api/posts/${id}/publish`,
  postBySlug: (slug: string) => `/api/posts/${slug}`,
} as const;
