export const UI_TEXT = {
  vi: {
    admin: {
      sections: {
        content: "NỘI DUNG",
        system: "HỆ THỐNG",
      },
      menu: {
        dashboard: "Bảng điều khiển",
        postManager: "Quản lý bài viết",
        configManager: "Quản lý cấu hình",
      },
      layout: {
        appLabel: "CMS Quản trị",
        appTitle: "Quản trị nội dung",
        appDescription: "Hệ thống dành cho cán bộ được phân quyền.",
        roleFallback: "quản trị viên",
        userFallback: "Quản trị viên",
        logout: "Đăng xuất",
        backToSite: "Về website",
        breadcrumbRoot: "Quản trị",
      },
      common: {
        loadingAdminData: "Đang tải dữ liệu quản trị...",
        adminDataLoadError: "Không thể tải dữ liệu quản trị viên.",
        unauthorizedViewOnly: "Quyền hiện tại",
        unauthorizedViewOnlySuffix: "Bạn chỉ có thể xem bảng điều khiển.",
        save: "Lưu",
        saving: "Đang lưu...",
        cancel: "Hủy",
        noData: "Không có dữ liệu.",
      },
      status: {
        draft: "Bản nháp",
        published: "Đã xuất bản",
      },
      postManager: {
        metricsTotalTitle: "Tổng bài viết",
        metricsTotalDesc: "Tất cả nội dung trong CMS",
        metricsPublishedTitle: "Đã xuất bản",
        metricsPublishedDesc: "Bài công khai trên website",
        metricsDraftTitle: "Bản nháp",
        metricsDraftDesc: "Bài đang chờ kiểm duyệt",
        title: "Quản lý bài viết",
        description: "Tìm kiếm, phân trang, chỉnh sửa, xuất bản và xóa nội dung theo vai trò.",
        createPost: "Tạo bài viết",
        searchPlaceholder: "Tìm theo tiêu đề, slug hoặc tác giả",
        showingCountPrefix: "Hiển thị",
        showingCountMiddle: "/",
        showingCountSuffix: "bài viết",
        tableTitle: "Tiêu đề",
        tableSlug: "Slug",
        tableStatus: "Trạng thái",
        tableAuthor: "Tác giả",
        tableActions: "Thao tác",
        thumbnailFallback: "Chưa có thumbnail",
        actionEdit: "Sửa",
        actionPublish: "Xuất bản",
        actionDelete: "Xóa",
        emptyFiltered: "Không có bài viết phù hợp.",
        pageLabel: "Trang",
        previousPage: "Trang trước",
        nextPage: "Trang sau",
        modalCreateTitle: "Tạo bài viết",
        modalUpdateTitle: "Cập nhật bài viết",
        modalDescription: "Bài viết sẽ được lưu ở trạng thái bản nháp. Chỉ admin mới có thể xuất bản.",
        fieldTitle: "Tiêu đề",
        fieldThumbnail: "Đường dẫn thumbnail",
        fieldContent: "Nội dung",
        saveDraft: "Lưu nháp",
        savePostError: "Không thể lưu bài viết.",
        publishPostError: "Không thể xuất bản bài viết.",
        deletePostError: "Không thể xóa bài viết.",
        savePostSuccess: "Bài viết đã được lưu.",
        publishPostSuccess: "Bài viết đã được xuất bản.",
        deletePostSuccess: "Bài viết đã bị xóa.",
        confirmDeletePrefix: "Xóa bài viết",
      },
      dashboard: {
        title: "Tổng quan CMS",
        description: "Bảng điều khiển hỗ trợ theo dõi nhanh tình trạng nội dung.",
        totalContent: "Tổng nội dung",
        latestPostsTitle: "Bài viết cập nhật gần đây",
        latestPostsDesc: "Danh sách các bài mới nhất để điều phối nội dung nhanh hơn.",
        latestPostsEmpty: "Chưa có bài viết nào.",
        checklistTitle: "Checklist vận hành",
        checklistItems: [
          "Kiểm tra bài nháp",
          "Xuất bản bài cần thông báo",
          "Rà soát cấu hình giao diện",
        ],
        syncNote: "Dữ liệu được đồng bộ từ API CMS.",
        stats: {
          activitiesTitle: "Hoạt động đơn vị",
          activitiesNote: "Tin bài trong hệ thống",
          guongBacTitle: "Theo gương Bác",
          guongBacNote: "Nội dung nội bộ",
          libraryTitle: "Thư viện",
          libraryNote: "Tư liệu, hiện vật, video",
          digitalLearningTitle: "Bình dân học vụ số",
          digitalLearningNote: "Chuyên đề số",
        },
      },
      config: {
        title: "Cấu hình hệ thống",
        description: "Quản lý header, menu và footer bằng các khối cấu hình riêng biệt.",
        adminRequired: "Chỉ admin mới có quyền cập nhật cấu hình hệ thống.",
      },
      menuManager: {
        title: "Quản lý menu",
        description: "Thêm, sửa, ẩn/hiện và sắp xếp menu theo cấu trúc cha - con.",
        addMenu: "Thêm menu",
        saveMenu: "Lưu menu",
        menuSaved: "Menu đã được lưu.",
        menuSaveError: "Không thể lưu menu.",
        menuItemFallback: "Mục menu",
        addChild: "Thêm mục con",
        childrenTitle: "Mục con",
        fieldMenuName: "Tên menu",
        fieldPath: "Đường dẫn",
        fieldChildName: "Tên mục con",
        newMenuLabel: "Mục mới",
        newChildLabel: "Mục con mới",
      },
      headerSettings: {
        title: "Cấu hình header",
        description: "Quản lý logo, tiêu đề và khẩu hiệu hiển thị ở đầu trang.",
        fieldLogo: "Logo",
        fieldTitle: "Tiêu đề",
        fieldSubtitle: "Khẩu hiệu",
        logoPreviewAlt: "Xem trước logo header",
        save: "Lưu Header",
        saveSuccess: "Header đã được lưu.",
        saveError: "Không thể lưu Header.",
      },
      footerSettings: {
        title: "Cấu hình footer",
        description: "Quản lý nội dung footer: liên hệ, liên kết và bản quyền.",
        fieldTitle: "Tiêu đề",
        fieldDescriptionLines: "Mô tả (mỗi dòng một mục)",
        quickLinks: "Liên kết nhanh",
        addLink: "Thêm link",
        labelPlaceholder: "Nhãn",
        hrefPlaceholder: "Đường dẫn",
        contactLines: "Thông tin liên hệ (mỗi dòng một mục)",
        copyright: "Bản quyền",
        save: "Lưu Footer",
        saveSuccess: "Footer đã được lưu.",
        saveError: "Không thể lưu Footer.",
      },
    },
  },
  en: {
    admin: {
      sections: {
        content: "CONTENT",
        system: "SYSTEM",
      },
    },
  },
} as const;
